Repository andela/ah-kgl-avengers-frontend, pull requests merged in 2019-06, with the labels that each got.

#1 #165020155 Setup an empty react project
  .babelrc
  .env.sample
  .eslintrc
  .github/commit_message_template.md
  .github/pull_request_template.md
  .gitignore
  .hound.yml
  README.md
  mockups/article-editor/article-editor.html
  mockups/article-editor/editor.css
  mockups/assets/.DS_Store
  mockups/assets/ah-logo 96x96.png
  mockups/assets/ah-logo-text-white.png
  mockups/assets/ah-logo12.png
  mockups/assets/ah_logo_A1_Rectangle_54_pattern.png
  mockups/assets/developers_2_A1_Rectangle_58_pattern.png
  mockups/assets/developers_5_A0_Rectangle_35_pattern.png
  mockups/assets/developers_6_A0_Rectangle_39_pattern.png
  mockups/assets/developers_8_A0_Rectangle_37_pattern.png
  mockups/assets/facebook_logo_A0_Rectangle_29_pattern.png
  mockups/assets/gmail_logo_A0_Rectangle_33_pattern.png
  mockups/assets/twitter_logo_A0_Rectangle_31_pattern.png
  mockups/button.css
  mockups/grid.css
  mockups/landing-page/landingpage.css
  mockups/landing-page/landingpage.html
  mockups/main.css
  mockups/profile-page/profile-edit.html
  mockups/profile-page/profile-followers.html
  mockups/profile-page/profile-update.html
  mockups/profile-page/profile.css
  mockups/profile-page/profile.html
  mockups/read-article/article.css
  mockups/read-article/article.html
  mockups/reset-password/logo.png
  mockups/reset-password/reset-confirmation.html
  mockups/reset-password/resetPassword.html
  mockups/reset-password/style.css
  mockups/reset-password/update-success.html
  mockups/reset-password/updatePassword.html
  mockups/signinTemplate/signin.css
  mockups/signinTemplate/signin.html
  mockups/signupview/signup.css
  mockups/signupview/signup.html
  package-lock.json
  package.json
  public/index.html
  src/app.jsx
  src/index.css
  src/index.js
  webpack.config.babel.js
Labels: TTL review, developer review

#4 #165020157 Setup test environment
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/__mocks__/fileMock.js
  src/__mocks__/styleMock.js
  src/__tests__/App.test.js
Labels: peer review

#2 #165020158 Configure CircleCI to run tests
  .circleci/config.yml
  README.md
Labels: peer review

#3 #165020159 Setting up react-router-v5
  .env.example
  .env.sample
  .gitignore
  README.md
  package-lock.json
  package.json
  src/app.jsx
Labels: ready to merge

#6 #165020160 setup SASS processing on the client
  package-lock.json
  package.json
  src/app.jsx
  src/index.scss
  webpack.config.babel.js
Labels: peer review

#5 #165020156 Setup Redux
  .babelrc
  .env.example
  README.md
  enzyme.config.js
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/App.test.js
  src/__tests__/__snapshots__/App.test.js.snap
  src/__tests__/actions/welcome.test.js
  src/__tests__/components/__snapshots__/welcome.test.js.snap
  src/__tests__/components/welcome.test.js
  src/__tests__/helpers/config.test.js
  src/__tests__/reducers/welcome.test.js
  src/app.jsx
  src/components/Welcome.jsx
  src/helpers/config.js
  src/index.js
  src/redux/action-creators/welcome.js
  src/redux/action-types/welcome.js
  src/redux/initialState.js
  src/redux/reducers/rootReducer.js
  src/redux/reducers/welcome.js
  src/redux/store/store.js
  webpack.config.babel.js
Labels: TTL review, peer review

#9 #166495422 Create a home page
  package-lock.json
  package.json
  public/favicon.png
  public/index.html
  src/__tests__/components/__snapshots__/navbar.test.js.snap
  src/__tests__/components/navbar.test.js
  src/__tests__/components/welcome.test.js
  src/app.jsx
  src/assets/images/ah-logo-text.png
  src/assets/images/ah_logo.png
  src/components/container/Welcome.jsx
  src/components/functional/footer.jsx
  src/components/functional/navBar.jsx
  src/components/functional/navigation.jsx
  src/index.scss
Labels: TTL review, peer review

#12 #165020162 User Signup
  .gitignore
  cypress/videos/App.spec.js.mp4
  mockups/assets/.DS_Store
  public/index.html
  src/__tests__/actions/signup.test.js
  src/__tests__/components/__snapshots__/signup.test.js.snap
  src/__tests__/components/signup.test.js
  src/__tests__/reducers/signup.test.js
  src/app.jsx
  src/assets/ah_logo_A1_Rectangle_54_pattern.png
  src/assets/developers_2_A1_Rectangle_58_pattern.png
  src/assets/developers_5_A0_Rectangle_35_pattern.png
  src/components/Auth/Nav.jsx
  src/components/Auth/Redirect.jsx
  src/components/Auth/Side.jsx
  src/components/Auth/Signup.jsx
  src/components/Auth/Title.jsx
  src/index.scss
  src/redux/action-creators/signup.js
  src/redux/action-types/auth.js
  src/redux/initialState.js
  src/redux/reducers/rootReducer.js
  src/redux/reducers/signup.js
  src/redux/store/store.js
  src/styles/Auth/_aside.scss
  src/styles/Auth/_nav.scss
  src/styles/Auth/_signup.scss
  src/styles/base.scss
  src/styles/button.scss
Labels: TTL review, peer review

#8 #165020164 User Login
  package-lock.json
  package.json
  public/index.html
  src/__tests__/actions/welcome.test.js
  src/__tests__/components/__snapshots__/welcome.test.js.snap
  src/__tests__/components/welcome.test.js
  src/__tests__/reducers/signup.test.js
  src/__tests__/reducers/welcome.test.js
  src/app.jsx
  src/assets/sign-in-img.png
  src/components/Auth/Signup.jsx
  src/components/Auth/login.jsx
  src/components/container/Welcome.jsx
  src/components/nav.jsx
  src/components/side.jsx
  src/redux/action-creators/signup.js
  src/redux/action-creators/user.js
  src/redux/action-creators/welcome.js
  src/redux/action-types/user.js
  src/redux/action-types/welcome.js
  src/redux/initialState.js
  src/redux/reducers/rootReducer.js
  src/redux/reducers/signup.js
  src/redux/reducers/user.js
  src/redux/reducers/welcome.js
  src/redux/store/store.js
  src/styles/Auth/_nav.scss
Labels: TTL review, peer review

#10 #165020167 Create, read, and update article(CRU)
  .netlify/state.json
  mockups/read-article/article.html
  package-lock.json
  package.json
  public/index.html
  src/__tests__/actions/editor.test.js
  src/__tests__/actions/readArticle.js
  src/__tests__/components/__snapshots__/chips.test.js.snap
  src/__tests__/components/__snapshots__/editor.test.js.snap
  src/__tests__/components/__snapshots__/messenger.test.js.snap
  src/__tests__/components/__snapshots__/readArticle.test.js.snap
  src/__tests__/components/__snapshots__/welcome.test.js.snap
  src/__tests__/components/chips.test.js
  src/__tests__/components/editor.test.js
  src/__tests__/components/messenger.test.js
  src/__tests__/components/readArticle.test.js
  src/__tests__/components/welcome.test.js
  src/__tests__/reducers/article.test.js
  src/app.jsx
  src/components/articleTitle.jsx
  src/components/chips/chips.jsx
  src/components/chips/chips.scss
  src/components/container/Welcome.jsx
  src/components/date.jsx
  src/components/description.jsx
  src/components/editor/ckConfig.js
  src/components/editor/editor.jsx
  src/components/editor/editor.scss
  src/components/editor/message.jsx
  src/components/functional/footer.jsx
  src/components/image.jsx
  src/components/imageAvatar.jsx
  src/components/ratingStars.jsx
  src/components/readArticle.jsx
  src/components/readTime.jsx
  src/components/status.jsx
  src/components/textArea.jsx
  src/components/userNames.jsx
  src/helpers/config.js
  src/helpers/readArticle.js
  src/images/lion.jpg
  src/images/lion.png
  src/index.scss
  src/redux/action-creators/index.js
  src/redux/action-creators/readArticle.js
  src/redux/action-creators/user.js
  src/redux/action-types/index.js
  src/redux/action-types/readArticle.js
  src/redux/initialState.js
  src/redux/reducers/article.js
  src/redux/reducers/readArticle.js
  src/redux/reducers/rootReducer.js
  src/redux/store/store.js
  src/scss/readArticle.scss
  webpack.config.babel.js
Labels: work in progress

#7 #166406459 setup end-to-end tests
  .circleci/config.yml
  .gitignore
  .travis.yml
  cy-coverage/lcov-report/base.css
  cy-coverage/lcov-report/block-navigation.js
  cy-coverage/lcov-report/index.html
  cy-coverage/lcov-report/prettify.css
  cy-coverage/lcov-report/prettify.js
  cy-coverage/lcov-report/sort-arrow-sprite.png
  cy-coverage/lcov-report/sorter.js
  cy-coverage/lcov.info
  cypress.json
  cypress/fixtures/example.json
  cypress/fixtures/profile.json
  cypress/fixtures/users.json
  cypress/integration/App.spec.js
  cypress/integration/Auth/signup.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/videos/App.spec.js.mp4
  jest.config.js
  package-lock.json
  package.json
  src/components/Auth/Signup.jsx
  src/redux/action-creators/welcome.js
Labels: TTL review, peer review

#17 #166699406 creates connectivity among components
  cypress/integration/App.spec.js
  cypress/videos/App.spec.js.mp4
  src/__tests__/components/navbar.test.js
  src/__tests__/components/welcome.test.js
  src/components/Auth/Signup.jsx
  src/components/Auth/login.jsx
  src/components/functional/navBar.jsx
Labels: TTL review, peer review

#18 #166699838 Change Navbar after Login
  cypress/integration/App.spec.js
  src/__tests__/components/welcome.test.js
  src/components/functional/footer.jsx
  src/components/functional/navBar.jsx
  src/index.scss
  src/styles/Auth/_nav.scss
Labels: TTL review, peer review

#14 #166727791 Get all published and drafts articles
  package-lock.json
  package.json
  src/__tests__/components/__snapshots__/articles.js.snap
  src/__tests__/components/__snapshots__/login.test.js.snap
  src/__tests__/components/articles.js
  src/__tests__/components/login.test.js
  src/__tests__/helpers/config.test.js
  src/app.jsx
  src/components/Auth/login.jsx
  src/components/articles.jsx
  src/components/editor/editor.jsx
  src/components/readArticle.jsx
  src/helpers/config.js
  src/redux/action-creators/editArticle.js
  src/redux/action-creators/getArticles.js
  src/redux/action-creators/getDrafts.js
  src/redux/action-types/editArticle.js
  src/redux/action-types/getArticles.js
  src/redux/initialState.js
  src/redux/reducers/article.js
  src/redux/reducers/getArticles.js
  src/redux/reducers/getDrafts.js
  src/redux/reducers/rootReducer.js
  src/styles/articles.scss
  src/styles/base.scss
Labels: ready to merge

#15 #166699331 Delete authored articles
  package-lock.json
  src/__tests__/actions/editor.test.js
  src/__tests__/actions/readArticle.js
  src/__tests__/components/articles.js
  src/__tests__/components/readArticle.test.js
  src/__tests__/reducers/article.test.js
  src/app.jsx
  src/components/articles.jsx
  src/components/delete/deleteConfirmation.jsx
  src/components/readArticle.jsx
  src/redux/action-creators/index.js
  src/redux/action-creators/readArticle.js
  src/redux/action-types/index.js
  src/redux/initialState.js
  src/redux/reducers/article.js
  src/redux/reducers/getArticles.js
  src/redux/reducers/getDrafts.js
  src/redux/reducers/readArticle.js
  src/redux/reducers/rootReducer.js
  src/styles/articles.scss
Labels: TTL review, peer review

#13 #165020163 User should be able to reset password
  public/_redirects
  src/__tests__/components/__snapshots__/reset.test.js.snap
  src/__tests__/components/reset.test.js
  src/app.jsx
  src/components/Auth/login.jsx
  src/components/container/requestReset.jsx
  src/components/container/updatePassword.jsx
  src/components/functional/card.jsx
  src/components/functional/navBar.jsx
  src/components/functional/resetModal.jsx
  src/index.scss
  src/redux/action-creators/resetPassword.js
  src/redux/action-types/resetPassword.js
  src/redux/reducers/resetPassword.js
  src/redux/reducers/rootReducer.js
  webpack.config.babel.js
Labels: TTL review, peer review

#20 #165020172 Show tags for each article
  jest.config.js
  src/__tests__/actions/feed.test.js
  src/__tests__/actions/readArticle.js
  src/__tests__/actions/readArticle.test.js
  src/__tests__/actions/reset.test.js
  src/__tests__/actions/signup.test.js
  src/__tests__/actions/user.test.js
  src/__tests__/components/__snapshots__/articles.test.js.snap
  src/__tests__/components/__snapshots__/login.test.js.snap
  src/__tests__/components/__snapshots__/readArticle.test.js.snap
  src/__tests__/components/__snapshots__/requestReset.test.js.snap
  src/__tests__/components/__snapshots__/updatePassword.test.js.snap
  src/__tests__/components/articles.js
  src/__tests__/components/articles.test.js
  src/__tests__/components/chips.test.js
  src/__tests__/components/editor.test.js
  src/__tests__/components/login.test.js
  src/__tests__/components/navbar.test.js
  src/__tests__/components/readArticle.test.js
  src/__tests__/components/requestReset.test.js
  src/__tests__/components/reset.test.js
  src/__tests__/components/signup.test.js
  src/__tests__/components/smallComponent.test.js
  src/__tests__/components/updatePassword.test.js
  src/__tests__/components/welcome.test.js
  src/__tests__/helpers/readArticle.test.js
  src/components/Auth/login.jsx
  src/components/container/Welcome.jsx
  src/components/editor/editor.jsx
  src/components/functional/chip.jsx
  src/components/functional/navBar.jsx
  src/components/nav.jsx
  src/components/readArticle.jsx
  src/components/singleArticle.jsx
  src/helpers/config.js
  src/helpers/readArticle.js
  src/redux/action-creators/user.js
  src/styles/articles.scss
  src/styles/readArticle.scss
Labels: TTL review, peer review

#19 #165020168 Add ratings
  package-lock.json
  package.json
  public/index.html
  src/__tests__/actions/readArticle.test.js
  src/components/readArticle.jsx
  src/images/avatar.png
  src/images/star.png
  src/redux/action-creators/rateArticle.js
  src/redux/action-creators/readArticle.js
  src/redux/action-types/rateArticle.js
  src/redux/initialState.js
  src/redux/reducers/article.js
  src/styles/readArticle.scss
Labels: ready to merge

#23 #165020166 User can view and edit profile
  src/__tests__/actions/feed.test.js
  src/__tests__/actions/profile.test.js
  src/__tests__/components/__snapshots__/profile.test.js.snap
  src/__tests__/components/profile.test.js
  src/__tests__/components/welcome.test.js
  src/__tests__/reducers/user.test.js
  src/app.jsx
  src/components/container/Welcome.jsx
  src/components/container/profile.jsx
  src/components/container/profileEditor.jsx
  src/components/functional/navBar.jsx
  src/components/imageAvatar.jsx
  src/components/singleArticle.jsx
  src/helpers/decodeToken.js
  src/helpers/imageUpLoader.js
  src/redux/action-creators/profile.js
  src/redux/action-types/index.js
  src/redux/reducers/user.js
  src/styles/Auth/_nav.scss
  src/styles/base.scss
  src/styles/profile.scss
Labels: TTL review, peer review

#21 #165020171 Add a like or dislike on an article
  .circleci/config.yml
  cypress/integration/Auth/login.spec.js
  cypress/integration/articles/addArticle.spec.js
  cypress/videos/App.spec.js.mp4
  src/__tests__/actions/readArticle.js
  src/__tests__/actions/readArticle.test.js
  src/components/Auth/Signup.jsx
  src/components/readArticle.jsx
  src/redux/action-creators/readArticle.js
  src/redux/action-types/getArticles.js
  src/redux/action-types/index.js
  src/redux/reducers/article.js
  src/styles/profile.scss
  src/styles/readArticle.scss
Labels: TTL review, peer review

#22 #165020165 creates login using google and facebook
  cypress.json
  cypress/integration/Auth/login.spec.js
  cypress/integration/Auth/signup.spec.js
  cypress/videos/App.spec.js.mp4
  package-lock.json
  package.json
  src/__tests__/actions/user.test.js
  src/__tests__/components/signup.test.js
  src/__tests__/components/socialLogin.test.js
  src/__tests__/reducers/user.test.js
  src/app.jsx
  src/components/Auth/Signup.jsx
  src/components/Auth/login.jsx
  src/components/Auth/socialLogin.jsx
  src/redux/action-creators/user.js
  src/redux/action-types/user.js
  src/redux/reducers/user.js
  src/styles/Auth/_signup.scss
Labels: ready to merge
